#!/data/data/com.termux/files/usr/bin/env bash

c1="\e[1;32m" # Green
c2="\e[39m" # Wite
STOP="\e[0m"

LOGO="
         -o          o-
          +hydNNNNdyh+
        +mMMMMMMMMMMMMm+
      \`dMM${c2}m:${c1}NMMMMMMN${c2}:m${c1}MMd\`
      hMMMMMMMMMMMMMMMMMMh
  ..  yyyyyyyyyyyyyyyyyyyy  ..
.mMMm\`MMMMMMMMMMMMMMMMMMMM\`mMMm.
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:
-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-
 +yy+ MMMMMMMMMMMMMMMMMMMM +yy+
      mMMMMMMMMMMMMMMMMMMm
      \`/++MMMMh++hMMMM++/\`
          MMMMo  oMMMM
          MMMMo  oMMMM
          oNMm-  -mMNs
"

printf "${c1}${LOGO}${STOP}"

